services:
  ss-mysql:
    container_name: ss-mysql
    image: mysql:latest
    hostname: ss-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: io_ss